// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: StructureEditor.tlb

[
  uuid(A91AA076-8091-48A7-9F9B-B59BDAF78127),
  version(1.0),
  helpstring("Solid Edge Structure Editor Object Library"),
  custom(DE77BA64-517C-11D1-A2DA-0000F8773CE9, 117441067),
  custom(DE77BA63-517C-11D1-A2DA-0000F8773CE9, 1338209111),
  custom(DE77BA65-517C-11D1-A2DA-0000F8773CE9, "Created by MIDL version 7.00.0555 at Mon May 28 07:45:11 2012
")

]
library StructureEditor
{
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    dispinterface ISEECStructureEditor;
    dispinterface ISEECStructureEditorATP;
    dispinterface IStructureEditor;

    [
      uuid(63CDA93E-2B12-423F-9071-D8202335244F),
      helpstring("SEEC Structure Editor Object")
    ]
    dispinterface ISEECStructureEditor {
        properties:
        methods:
            [id(0x00000001)]
            long ValidateLogin(
                            [in] BSTR bstrUserName, 
                            [in] BSTR bstrUserPassword, 
                            [in] BSTR bstrUserGroup, 
                            [in] BSTR bstrUserRole, 
                            [in] BSTR bstrDBUrl);
            [id(0x00000002)]
            long Open(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName, 
                            [in] BSTR bstrRevisionRule, 
                            [in] BSTR bstrFolderName);
            [id(0x00000003)]
            long SetSaveAsAll();
            [id(0x00000004)]
            long SetSaveAsSelected(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName);
            [id(0x00000005)]
            long SetReviseAll();
            [id(0x00000006)]
            long SetReviseSelected(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName, 
                            [in, optional] BSTR szPrntItemId, 
                            [in, optional] BSTR szPrntItemRev, 
                            [in, optional] BSTR szPrntDataSetFileName);
            [id(0x00000007)]
            long AssignAll();
            [id(0x00000008)]
            long PerformActions();
            [id(0x00000009)]
            long ClearAllActions();
            [id(0x0000000a)]
            long Close();
            [id(0x00000010)]
            long SetReplaceSelected(
                            [in] BSTR bstrSourceItemId, 
                            [in] BSTR bstrSourceItemRev, 
                            [in] BSTR bstrSourceDataSetFileName, 
                            [in] BSTR bstrTargetItemId, 
                            [in] BSTR bstrTargetItemRev, 
                            [in] BSTR bstrTargetDataSetFileName, 
                            [in] BSTR bstrRevisionRule, 
                            [in] BSTR bstrParentItemId, 
                            [in] BSTR bstrParentItemRev, 
                            [in] BSTR bstrParentDataSetFileName, 
                            [in] BSTR bstrSrcFOAMemberName, 
                            [in] BSTR bstrTgtFOAMemberName);
            [id(0x00000011)]
            long GetProjectsForLoggedInUser([out] VARIANT* pvarListOfProjects);
            [id(0x00000012)]
            long GetProjectsForGivenItemID(
                            [in] BSTR bstrItemId, 
                            [out] VARIANT* pvarListOfProjects);
            [id(0x00000013)]
            long AddItemToGivenProjects(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName, 
                            [in] BSTR bstrUserProjects);
            [id(0x00000014)]
            long AddExistingItem(
                            [in] BSTR szItemId, 
                            [in] BSTR szItemRev, 
                            [in] BSTR szDataSetFileName, 
                            [in] BSTR szItemIdToBeAdded, 
                            [in] BSTR szItemRevToBeAdded, 
                            [in] BSTR szDataSetFileNameToBeAdded, 
                            [in] BSTR szRevisionRule);
            [id(0x00000015)]
            long AddNewItem(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName);
            [id(0x00000016)]
            long RemoveItem(
                            [in] BSTR szPrntItemId, 
                            [in] BSTR szPrntItemRev, 
                            [in] BSTR szPrntDataSetFileName, 
                            [in] BSTR szItemIdToBeRemoved, 
                            [in] BSTR szTgtItemRevToBeRemoved, 
                            [in] BSTR szTgtDataSetFileNameToBeRemoved);
            [id(0x00000017)]
            long CreateRootNewItem();
            [id(0x00000018)]
            long AddItemInMultipleFiles(
                            [in] VARIANT* pVarListOfParentItemsInfo, 
                            [in] BSTR szItemIdToBeAdded, 
                            [in] BSTR szItemRevToBeAdded, 
                            [in] BSTR szDataSetFileNameToBeAdded, 
                            [in] BSTR szRevisionRule);
            [id(0x00000019)]
            long SetSaveAsSpecificOccurrence(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrDataSetFileName, 
                            [in] BSTR szPrntItemId, 
                            [in] BSTR szPrntItemRev, 
                            [in] BSTR szPrntDataSetFileName);
    };

    [
      uuid(070F7A6C-8621-466C-9318-92461EC1B716),
      helpstring("SEEC Structure Editor Object")
    ]
    coclass SEECStructureEditor {
        [default] dispinterface ISEECStructureEditor;
    };

    [
      uuid(4118A328-2720-4107-9757-374178390133),
      helpstring("SEEC Structure Editor ATP Object")
    ]
    dispinterface ISEECStructureEditorATP {
        properties:
        methods:
            [id(0x00000001)]
            long WriteStructureEditorDevLog([in] BSTR bstrLogMessage);
            [id(0x00000002)]
            long GetStructureEditorTALLogFileName([out] BSTR* bstrTALLogFileName);
            [id(0x00000003)]
            long SetStructureEditorATPRunning([in] VARIANT_BOOL bMode);
            [id(0x00000004)]
            long SetStructureEditorATPInfo(
                            [in] BSTR bstrATPClassName, 
                            [in] BSTR bstrATPName, 
                            [in] long lATPId);
            [id(0x00000005)]
            long SetFolderCellToNewStuff();
            [id(0x00000006)]
            long SetDataIntoCell(
                            [in] BSTR bstrItemId, 
                            [in] BSTR bstrItemRev, 
                            [in] BSTR bstrFileName, 
                            [in] BSTR bstrPropName, 
                            [in] BSTR bstrPropVal);
            [id(0x00000007)]
            long SetCrashStructureEditorMacroFileName([in] BSTR bstrFileName);
            [id(0x00000008)]
            long SetCrashStructureEditorMicroFileName([in] BSTR bstrFileName);
            [id(0x00000009)]
            long VerifyBOMForReplace([out] BSTR* bstrErrorMessage);
            [id(0x00000013)]
            long SetMessageForSmartCode([in] VARIANT* pvarListOfMessages);
            [id(0x00000014)]
            long SetValuesForSmartCode([in] VARIANT* pvarListOfValues);
            [id(0x00000015)]
            long ShowFileOpenDialog();
    };

    [
      uuid(C8EDF44D-2C0E-4956-9709-A438528FD52A),
      helpstring("SEEC Structure Editor ATP Object")
    ]
    coclass SEECStructureEditorATP {
        [default] dispinterface ISEECStructureEditorATP;
    };

    [
      uuid(E49F21BD-C7B8-4DEA-83E6-F9642F20D088),
      helpstring("Structure Editor Application")
    ]
    dispinterface IStructureEditor {
        properties:
            [id(0x00000001)            
]
            IDispatch* Application;
            [id(0x00000002)            
]
            IDispatch* Parent;
            [id(0x00000003)            
]
            long Visible;
        methods:
            [id(0x00000004), propget]
            IDispatch* SEECStructureEditor();
            [id(0x00000005), propget]
            IDispatch* SEECStructureEditorATP();
            [id(0x00000006)]
            void Quit();
            [id(0x00000007)]
            long SetDisplayAlerts([in] VARIANT_BOOL bDisplayAlerts);
            [id(0x00000008)]
            long GetDisplayAlerts([out] VARIANT_BOOL* bDisplayAlerts);
            [id(0x00000009)]
            long SetBOMViewInCombo([in] LPWSTR bstrBOMView);
            [id(0x0000000a)]
            long GetBOMViewSetInCombo([out] BSTR* pbstBOMView);
    };

    [
      uuid(064642EA-9913-4303-9C3E-B1E5AE467231),
      helpstring("Structure Editor Application")
    ]
    coclass Application {
        [default] dispinterface IStructureEditor;
    };
};
